<script lang="ts">
  import PConnect from '@/components/PolygonConnect/index.svelte'
  import { isConnect, myAddressShort } from '@/stores'
</script>

<div class="container">
  <div class="container-title">Lotus</div>
  <div class="container-content">
    <div class="container-paragraph">
      Lotus is the place that produces $Nectar. The Lotus generate 10 $Nectar per block generated by the polygonal
      blockchain. Approximately 370,000 $Nectar are generated a day.
      <br />
      Clones from Clones Never Die 萬' can bring $Nectar from the Lotus.
      <br />
      Send the clones to the Lotus and bring $Nectar!
    </div>
    <div class="sub-content">
      {#if $isConnect}
        <div class="connected">
          <b>
            {$myAddressShort}
          </b>
        </div>
      {:else}
        <div class="connectBtn">
          <PConnect />
        </div>
      {/if}
    </div>
    <div class="sub-frame">
      <div class="sub-content">
        <div class="sub-title"><b>Lotus Staking</b></div>
        <div class="sub-item">
          <div class="sub-item-wrap">
            <div class="sub-item-title"><b>Staking</b></div>
            <div class="sub-item-explain">
              로터스 스테이킹으로 클론즈를 스테이킹 합니다. 스테이킹할 클론을 선택하고 버튼을 눌러주세요
            </div>
            <div class="sub-item-title"><b>My Clones</b></div>
            <ul class="sub-item-list-head">
              <li class="list-item">
                <div class="item-number">Select</div>
                <div class="item-number">No.</div>
                <div class="item-name">Name</div>
                <div class="item-id">Token ID</div>
              </li>
            </ul>
            <ul class="sub-item-list">
              <li class="list-item">
                <input type="checkbox" name="asd" />
                <div class="item-number">1</div>
                <div class="item-name">CxNxD #0001</div>
                <div class="item-id">1</div>
              </li>
            </ul>
            <div class="sub-selected">Selected: 1, 2, 3, 4, 5</div>
            <div class="sub-btn">Staking</div>
          </div>
        </div>
      </div>
    </div>
    <div class="sub-frame">
      <div class="sub-content">
        <div class="sub-title"><b>My Staking</b></div>
        <div class="sub-item">
          <div class="sub-item-wrap">
            <div class="sub-item-title"><b>My Staking List</b></div>
            <div class="sub-item-explain">현재 나의 스테이킹 목록입니다. 넥타르를 민팅할 수 있습니다.</div>
            <ul class="sub-item-list-head">
              <li class="list-item">
                <div class="item-number">No.</div>
                <div class="item-number">Clones</div>
                <div class="item-name">Nectar</div>
                <div class="item-id">Detail</div>
              </li>
            </ul>
            <ul class="sub-item-list-long">
              <li class="list-item">
                <div class="item-number">1</div>
                <div class="item-number">9</div>
                <div class="item-number">10000000000</div>
                <div class="item-id"><button>ck</button></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="sub-content"></div>
  </div>
</div>

<style lang="scss">
  .container-content {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    width: 100%;
    min-height: 80vh;
    justify-content: space-between;
    align-items: flex-start;
  }

  .connectBtn {
    width: 200px;
    background-color: $highlight-color;
    font-size: 20px;
    border-radius: 10px;
    text-align: center;
    padding: 10px;
    box-sizing: border-box;
    cursor: pointer;
  }

  .container-paragraph {
    width: 60%;
  }

  .connected {
    width: 200px;
    background-color: $highlight-color;
    font-size: 20px;
    border-radius: 10px;
    text-align: center;
    padding: 10px;
    box-sizing: border-box;
  }

  .sub-content {
    width: 100%;
    margin-bottom: 40px;
  }

  .sub-title {
    color: $highlight-color;
    font-size: 1.2rem;
    margin-bottom: 20px;
  }

  .sub-frame {
    width: 50%;
    padding: 10px;
    box-sizing: border-box;
  }
  .sub-item {
    border: 2px solid $highlight-color;
    height: auto;
    box-sizing: border-box;
    border-radius: 10px;
  }

  .sub-item-wrap {
    padding: 30px;
    display: flex;
    height: 80%;
    flex-direction: column;
    justify-content: space-around;
  }

  .sub-item-title {
    font-size: 1.6rem;
    margin-bottom: 10px;
  }

  .sub-item-explain {
    font-size: 0.9rem;
    margin-bottom: 20px;
  }

  .sub-item-list {
    padding: 10px;
    height: 200px;
    overflow: scroll;
  }

  .sub-item-list-long {
    height: 345px;
    overflow: scroll;
  }

  .sub-item-list-head {
    box-sizing: border-box;
    border-radius: 10px;
  }

  .list-item {
    width: 100%;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 10px;
    font-size: 1rem;
  }

  .sub-btn {
    width: 100%;
    background-color: $highlight-color;
    font-size: 20px;
    border-radius: 10px;
    text-align: center;
    padding: 10px;
    box-sizing: border-box;
    cursor: pointer;
  }

  .sub-selected {
    margin-top: 10px;
    margin-bottom: 10px;
  }
  @media screen and (max-width: 768px) {
    .sub-frame {
      width: 1000%;
      padding: 10px;
      box-sizing: border-box;
    }
    .sub-item-wrap {
      padding: 15px;
    }
    .list-item {
      width: 100%;
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 10px;
      font-size: 0.7rem;
    }
    .sub-frame {
      width: 100%;
      padding: 0px;
    }

    .container-paragraph {
      width: 100%;
    }
  }
</style>
